window.defaultData = [
			{ "Item Name": "Casual Shoes", Date: "02/14/2014", Time: "11:34:32 AM", Quantity: 10, Price: "20", Amount: "200", Discount: "1", Profit: "10" },
			{ "Item Name": "Sports Shoes", Date: "06/11/2014", Time: "05:56:32 AM", Quantity: 20, Price: "30", Amount: "600", Discount: "5", Profit: "50" },
			{ "Item Name": "Formal Shoes", Date: "07/27/2014", Time: "03:32:44 AM", Quantity: 20, Price: "15", Amount: "300", Discount: "7", Profit: "27" },
			{ "Item Name": "Sandals & Floaters", Date: "11/21/2014", Time: "06:23:54 AM", Quantity: 15, Price: "20", Amount: "300", Discount: "11", Profit: "67" },
			{ "Item Name": "Flip- Flops & Slippers", Date: "06/23/2014", Time: "12:43:59 AM", Quantity: 30, Price: "10", Amount: "300", Discount: "10", Profit: "70" },
			{ "Item Name": "Sneakers", Date: "07/22/2014", Time: "10:55:53 AM", Quantity: 40, Price: "20", Amount: "800", Discount: "13", Profit: "66" },
			{ "Item Name": "Running Shoes", Date: "02/04/2014", Time: "03:44:34 AM", Quantity: 20, Price: "10", Amount: "200", Discount: "3", Profit: "14" },
			{ "Item Name": "Loafers", Date: "11/30/2014", Time: "03:12:52 AM", Quantity: 31, Price: "10", Amount: "310", Discount: "6", Profit: "29" },
			{ "Item Name": "Cricket Shoes", Date: "07/09/2014", Time: "11:32:14 AM", Quantity: 41, Price: "30", Amount: "1210", Discount: "12", Profit: "166" },
			{ "Item Name": "T-Shirts", Date: "10/31/2014", Time: "12:01:44 AM", Quantity: 50, Price: "10", Amount: "500", Discount: "9", Profit: "55" },
            ];
window.conditionalFormat = [
              { "Item Name": "Text contains with Loafers", Date: "Loafers", Quantity: "", Price: "Date occur with 02/04/2014", Amount: "05/03/2013", Discount: "", Netamount: "Less than 30", Value: "5" },
              { "Item Name": "", Date: "Casual Shoes", Quantity: "", Price: "", Amount: "06/23/2014", Discount: "", Netamount: "", Value: "56" },
              { "Item Name": "", Date: "Loafers", Quantity: "", Price: "", Amount: "07/22/2014", Discount: "", Netamount: "", Value: "24" },
              { "Item Name": "", Date: "Formal Shoes", Quantity: "", Price: "", Amount: "02/04/2014", Discount: "", Netamount: "", Value: "12" },
              { "Item Name": "", Date: "Sandals & Floaters", Quantity: "", Price: "", Amount: "11/30/2014", Discount: "", Netamount: "", Value: "36" },
              { "Item Name": "", Date: "", Quantity: "", Price: "", Amount: "", Discount: "", Netamount: "", Value: "", Value1: "", Tax: "", Tax1: "" },
              { "Item Name": "Between 400 to 500", Date: "273", Quantity: "", Price: "Greater than 5000", Amount: "5003", Discount: "", Netamount: "Equal to 20", Value: "21" },
              { "Item Name": "", Date: "345", Quantity: "", Price: "", Amount: "3434", Discount: "", Netamount: "", Value: "34", Value1: "" },
              { "Item Name": "", Date: "494", Quantity: "", Price: "", Amount: "7553", Discount: "", Netamount: "", Value: "20", Value1: "" },
              { "Item Name": "", Date: "506", Quantity: "", Price: "", Amount: "2364", Discount: "", Netamount: "", Value: "20", Value1: "" },
              { "Item Name": "", Date: "453", Quantity: "", Price: "", Amount: "6788", Discount: "", Netamount: "", Value: "23", Value1: "" },
              ];
window.visaDetail = [
			{ ID: "Greater than 6", Type: "", TypeOfVisa: "Text Length Less than 35", Value: "", VisaFees: "Between 150 to 200", FNo: "", NoOfPassenger: "List", DDate: "", Date: "Greater than 07/09/2014", DTime: "", Time: "Greater than 11:23:23  AM" },
			{ ID: 1, Type: "", TypeOfVisa: "Business", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "1", DDate: "", Date: "02/14/2014", DTime: "", Time: "11:34:32 AM" },
			{ ID: 2, Type: "", TypeOfVisa: "Religious Worker", Value: "", VisaFees: "$190.00", FNo: "", NoOfPassenger: "2", DDate: "", Date: "06/11/2014", DTime: "", Time: "05:56:32 AM" },
			{ ID: 3, Type: "", TypeOfVisa: "Temporary Workers/Employment or Trainees", Value: "", VisaFees: "$190.00", FNo: "", NoOfPassenger: "3", DDate: "", Date: "03/04/2012", DTime: "", Time: "07:16:22 AM" },
			{ ID: 4, Type: "", TypeOfVisa: "Transiting the United States", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "4", DDate: "", Date: "07/27/2014", DTime: "", Time: "03:32:44 AM" },
			{ ID: 5, Type: "", TypeOfVisa: "Student, Academic", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "5", DDate: "", Date: "11/21/2014", DTime: "", Time: "06:23:54 AM" },
			{ ID: 6, Type: "", TypeOfVisa: "Orphan (Intercountry Adoption)", Value: "", VisaFees: "$720.00", FNo: "", NoOfPassenger: "6", DDate: "", Date: "06/23/2014", DTime: "", Time: "11:22:59 AM" },
			{ ID: 7, Type: "", TypeOfVisa: "Exchange Visitors", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "7", DDate: "", Date: "07/22/2014", DTime: "", Time: "10:55:53 AM" },
			{ ID: 8, Type: "", TypeOfVisa: "DV category Immigrant Visa", Value: "", VisaFees: "$360.00", FNo: "", NoOfPassenger: "8", DDate: "", Date: "07/22/2014", DTime: "", Time: "10:55:53 AM" },
			{ ID: 9, Type: "", TypeOfVisa: "Victims of Criminal Activity", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "8", DDate: "", Date: "02/04/2014", DTime: "", Time: "03:44:34 AM" },
			{ ID: 10, Type: "", TypeOfVisa: "NAFTA Professionals", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "9", DDate: "", Date: "11/30/2014", DTime: "", Time: "03:12:52 AM" },
			{ ID: 11, Type: "", TypeOfVisa: "Employment-Based Applications", Value: "", VisaFees: "$345.00", FNo: "", NoOfPassenger: "10", DDate: "", Date: "07/09/2014", DTime: "", Time: "11:32:14 AM" },
			{ ID: 12, Type:"",TypeOfVisa: "Intracompany Transferees", Value:"",VisaFees: "$190.00", FNo:"",NoOfPassenger: "11",DDate:"",Date: "10/31/2014", DTime:"", Time: "11:01:44 AM" },
			{ ID: 13, Type: "", TypeOfVisa: "Person with Extraordinary Ability", Value: "", VisaFees: "$190.00", FNo: "", NoOfPassenger: "12", DDate: "", Date: "07/22/2014", DTime: "", Time: "10:55:53 AM" },
			{ ID: 14, Type: "", TypeOfVisa: "Tourism", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "13", DDate: "", Date: "10/31/2014", DTime: "", Time: "11:01:44 AM" },
            ];
window.chartDetails = [
                { Name: "VINET", Average: 90, Grade: "S" },
				{ Name: "TOMSP", Average: 83, Grade: "A" },
				{ Name: "HANAR", Average: 80, Grade: "A" },
				{ Name: "VICTE", Average: 93, Grade: "S" },
				{ Name: "SUPRD", Average: 60, Grade: "D" },
				{ Name: "CHOPS", Average: 71, Grade: "C" },
				{ Name: "WELLI", Average: 88, Grade: "A" },
				{ Name: "HILLA", Average: 95, Grade: "S" },
				{ Name: "ERNSH", Average: 69, Grade: "D" },
				{ Name: "CENTC", Average: 77, Grade: "C" },
				{ Name: "OTTIK", Average: 95, Grade: "S" },
				{ Name: "RATTC", Average: 85, Grade: "A" },
				{ Name: "FOLKO", Average: 90, Grade: "A" },
				{ Name: "BLONP", Average: 97, Grade: "S" }
            ];
 window.moviesList = [
                    { no: "No", year: "YEAR", title: "TITLE", review: "REVIEW", actors: "STARRING ACTORS", director: "DIRECTOR", genre: "GENRE", rating: "RATING", format: "FORMAT", comments: "COMMENTS" },
                    { "no": 1, "year": 1994, "title": "Forrest Gump", "review": "5 Stars", "actors": "Tom Hanks, Robin Wright, Gary Sinise", "director": "Robert Zemeckis", "genre": "Drama", "rating": "PG-13", "format": "DVD", "comments": "Based on the 1986 novel of the same name by Winston Groom" },
                    { "no": 2, "year": 1946, "title": "It’s a Wonderful Life", "review": "2 Stars", "actors": "James Stewart, Donna Reed, Lionel Barrymore ", "director": "Frank Capra", "genre": "Drama", "rating": "G", "format": "VHS", "comments": "Colorized version" },
                    { "no": 3, "year": 1988, "title": "Big", "review": "4 Stars", "actors": "Tom Hanks, Elizabeth Perkins, Robert Loggia ", "director": "Penny Marshall", "genre": "Comedy", "rating": "PG", "format": "DVD", "comments": "" },
                    { "no": 4, "year": 1954, "title": "Rear Window", "review": "3 Stars", "actors": "James Stewart, Grace Kelly, Wendell Corey ", "director": "Alfred Hitchcock", "genre": "Suspense", "rating": "PG", "format": "Blu-ray", "comments": "" },
    ];