syncApp.controller('DataBindingRemoteCrtl', function ($scope, $interval) {
    $scope.reportServiceUrl = window.baseurl + 'api/ReportViewer';
    $scope.localMode = ej.ReportViewer.ProcessingMode.Local;
    $scope.rdlcReportPath = 'DatabindingRemote.rdlc';
    $scope.dataSource = jQuery.parseJSON("[{\"value\":[{\"OrderID\":10248,\"CustomerID\":\"VINET\",\"EmployeeID\":5,\"Freight\":32.38,\"ShipCity\":\"Reims\",\"ShipCountry\":\"France\"},{\"OrderID\":10249,\"CustomerID\":\"TOMSP\",\"EmployeeID\":6,\"Freight\":11.61,\"ShipCity\":\"Munster\",\"ShipCountry\":\"Germany\"},{\"OrderID\":10250,\"CustomerID\":\"HANAR\",\"EmployeeID\":4,\"Freight\":65.83,\"ShipCity\":\"Rio de Janeiro\",\"ShipCountry\":\"Brazil\"},{\"OrderID\":10251,\"CustomerID\":\"VICTE\",\"EmployeeID\":3,\"Freight\":41.34,\"ShipCity\":\"Lyon\",\"ShipCountry\":\"France\"},{\"OrderID\":10252,\"CustomerID\":\"SUPRD\",\"EmployeeID\":4,\"Freight\":51.3,\"ShipCity\":\"Charleroi\",\"ShipCountry\":\"Belgium\"},{\"OrderID\":10253,\"CustomerID\":\"HANAR\",\"EmployeeID\":3,\"Freight\":58.17,\"ShipCity\":\"Rio de Janeiro\",\"ShipCountry\":\"Brazil\"},{\"OrderID\":10254,\"CustomerID\":\"CHOPS\",\"EmployeeID\":5,\"Freight\":22.98,\"ShipCity\":\"Bern\",\"ShipCountry\":\"Switzerland\"},{\"OrderID\":10255,\"CustomerID\":\"RICSU\",\"EmployeeID\":9,\"Freight\":148.33,\"ShipCity\":\"Geneve\",\"ShipCountry\":\"Switzerland\"},{\"OrderID\":10256,\"CustomerID\":\"WELLI\",\"EmployeeID\":3,\"Freight\":13.97,\"ShipCity\":\"Resende\",\"ShipCountry\":\"Brazil\"},{\"OrderID\":10257,\"CustomerID\":\"HILAA\",\"EmployeeID\":4,\"Freight\":81.91,\"ShipCity\":\"San Christobal\",\"ShipCountry\":\"Venezuela\"},{\"OrderID\":10258,\"CustomerID\":\"ERNSH\",\"EmployeeID\":1,\"Freight\":140.51,\"ShipCity\":\"Graz\",\"ShipCountry\":\"Austria\"},{\"OrderID\":10259,\"CustomerID\":\"CENTC\",\"EmployeeID\":4,\"Freight\":3.25,\"ShipCity\":\"Mwxico D.F\",\"ShipCountry\":\"Mexico\"},{\"OrderID\":10260,\"CustomerID\":\"OTTIk\",\"EmployeeID\":4,\"Freight\":55.09,\"ShipCity\":\"Koln\",\"ShipCountry\":\"Germany\"},{\"OrderID\":10261,\"CustomerID\":\"QUEDE\",\"EmployeeID\":4,\"Freight\":3.05,\"ShipCity\":\"Rio de Janeiro\",\"ShipCountry\":\"Brazil\"}],\"name\":\"remote\"}]");

    $scope.success = function (args) {
        $compile(args.content)($scope);
    };
});