
syncApp.controller('FileExplorerLocalization', function ($scope, $window, $timeout) {
    $scope.ajaxaction = window.baseurl + "api/FileExplorer/FileOperations"; 
    $scope.path = window.baseurl + "Content/FileBrowser/";
	$scope.gridSettings = { 
		columns: [
			{ field: "name", headerText: "nombre", width: "30%" },
			{ field: "dateModified", headerText: "fecha de modificación", width: "30%" },
			{ field: "type", headerText: "tipo", width: "15%"  },
			{ field: "size", headerText: "tamaño", width: "12%" }]
			};
    ej.FileExplorer.Locale["es-ES"] = {
        EmptyResult: "Ningun articulo concuerda con su busqueda",
        EmptyFolder: "Esta carpeta está vacía",
        ProtectedFolder: "Actualmente no tiene permiso para acceder a esta carpeta",
        Back: "hacia atrás",
        Forward: "adelante",
        Upward: "Hacia arriba",
        Refresh: "refrescar",
        Addressbar: "Barra de dirección",
        Upload: "Subir",
        Rename: "rebautizar",
        Delete: "borrar",
        Download: "Descargar",
        Error: "error",
        Cut: "cortada",
        Copy: "copia",
        Paste: "pasta",
        Details: "Detalles",
        Searchbar: "barra de búsqueda",
        Open: "abierto",
        Search: "búsqueda",
        NewFolder: "Nueva Carpeta",
        SelectedFileUrl: "dirección Web",
        SelectedFileName: "título",
        ImageWidth: "ancho",
        ImageHeight: "altura",
        Insert: "Insertar",
        Cancel: "cancelar",
        RenameAlert: "Por favor, introduzca el nuevo nombre",
        NewFolderAlert: "Introduzca el nuevo nombre de la carpeta",
        ContextMenuOpen: "abierto",
        ContextMenuNewFolder: "nueva carpeta",
        ContextMenuDelete: "borrar",
        ContextMenuRename: "rebautizar",
        ContextMenuUpload: "Subir",
        ContextMenuDownload: "descargar",
        ContextMenuCut: "cortada",
        ContextMenuCopy: "copia",
        ContextMenuPaste: "pasta",
        ContextMenuGetinfo: "Obtén información",
        ContextMenuRefresh: "refrescar",
        ContextMenuOpenFolderLocation: "Ubicación de la carpeta abierta",
        ContextMenuSortBy: "Ordenar por",
        SortBy: "Ordenar por",
        Item: " artículo",
        Items: " artículos",
        Selected: "seleccionado",
        Permission: "Permiso",
        OkButton: "Okay",
        CancelButton: "cancelar",
        YesButton: "sí",
        NoButton: "No",
        YesToAllButton: "Si a todo",
        NoToAllButton: "No a todos",
        Size: "tamaño",
        Grid: "Vista de cuadrícula",
        Tile: "vista de mosaicos",
        LargeIcons: "Iconos grandes",
        Layout: "Diseño",
        SkipButton: "Omitir",
        ErrorOnFolderCreation: "Este destino ya contiene una carpeta llamada '{0}'. ¿Desea fusionar este contenido de la carpeta con la carpeta ya existente '{0}'?",
        InvalidFileName: "Un nombre de archivo no puede contener ninguno de los siguientes caracteres: \\/:*?\"<>|",
        GeneralError: "Por favor, vea ventana de la consola del navegador para obtener más información",
        ErrorPath: "FileExplorer no puede encontrar '{0}'. Revisa la ortografía y vuelva a intentarlo.",
        ReplaceAlert: "Archivo llamado '{0}' ya existe. Reemplazar archivo antiguo por uno nuevo?",
        DuplicateAlert: "Ya existe un archivo con el mismo nombre '{0}'. ¿Quieres crear el archivo con nombre duplicado",
        DuplicateFileCreation: "Ya existe un archivo con el mismo nombre en esta ubicación. ¿Quieres cambiar el nombre de '{0}' a '{1}'?",
        DeleteFolder: " Estas seguro que quieres borrarlo ",
        DeleteMultipleFolder: "¿Seguro que quieres eliminar estos {0} artículos?",
        CancelPasteAction: "La carpeta de destino es una subcarpeta de la carpeta de origen.",
        Name: "nombre",
        Location: "ubicación",
        Type: "Tipo De Artículo",
        Created: "creado",
        Modified: "Modificado",
        DialogCloseToolTip: "cerca",
        UploadSettings: {
            buttonText: {
                upload: "Subir",
                browse: "Explorar",
                cancel: "cancelar",
                close: "cerca"
            },
            dialogText: {
                title: "Subir Box",
                name: "nombre",
                size: "tamaño",
                status: "estado"
            },
            cancelToolTip: "cancelar",
            removeToolTip: "quitar",
            retryToolTip: "Reintente",
            completedToolTip: "terminado",
            failedToolTip: "fracasado",
            closeToolTip: "cerca"
        }
    };


})